New command environment-revision to retrieve currently active revision

diff --git a/rancherize b/rancherize
--- a/rancherize
+++ b/rancherize
@@ -279,6 +279,25 @@ case $1 in
 		fi
 
 		;;
+	environment-revision)
+		getParameter ENVIRONMENT "staging" "$2"
+
+		readEnvironmentConfig $SOURCE_ENVIRONMENT || exit 1
+
+		validateConfig || exit 2
+
+		OLDPWD="$PWD"
+		cd $DEPLOY_DIRECTORY
+
+		if ! update_compose $RANCHER_ACCESS_KEY $RANCHER_SECRET_KEY $RANCHER_API_URL $RANCHER_STACK_ID ; then
+			echo "Failed to update docker-compose.yml and rancher-compose.yml from server"
+			exit 4
+		fi
+
+		ENVIRONMENT_REVISION=$(find_version $RANCHER_SERVICE_NAME | xargs | sed "s/$RANCHER_SERVICE_NAME-//g")
+		echo "$ENVIRONMENT_REVISION"
+		cd "$OLDPWD"
+
 	pull-up)
 		getParameter SOURCE_ENVIRONMENT "staging" "$2"
 		getParameter TARGET_ENVIRONMENT "production" "$3"
